---
# Collections downloaded from classroom materials server
# Install with:
#   ansible-galaxy collection install -r collections/requirements.yml -p ./collections/
collections:
  - name: http://classroom/materials/redhat-insights-1.0.7.tar.gz
  - name: http://classroom/materials/community-general-5.5.0.tar.gz
  - name: http://classroom/materials/redhat-rhel_system_roles-1.19.3.tar.gz
