---
# Roles downloaded from classroom materials server
# Install with:
#   ansible-galaxy install -r roles/requirements.yml
- src: http://classroom/materials/haproxy.tar
  name: balancer

- src: http://classroom/materials/phpinfo.tar
  name: phpinfo
